services:
  - type: web
    name: daraa-events-site
    env: node
    plan: free
    buildCommand: npm install --build-from-source=sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
